### PR TITLE
Branch ui() and config_file() into their own file and class

### LINKED ISSUE #4: Variables hard_drive, host_name, etc shouldn't need to be globals
These variables should already be accessible due to the way they were initialized.

### PR DESCRIPTION
**Pull request by TheMowgliMan**
### Description
Moves the above functions in `install.py` into `installClass.py`. Should fix #4, and gives us something neater to work with until #2 is fixed.

### Limitations
I haven't tested it, although it's a fairly elementary change that should have no effects. I know that all variables that were undefined because of `5140789` and `eb483f3` are now redefined as members of `installerClass`.

In addition, the rest of the code currently in `install.py` should be moved into `installClass.py` at some point.

### CODE REVIEW

**Comment by michaeleldar** [comment]
The problem is, the user then has to download both files and that just adds extra complexity, which we already have too much of?

**Comment by TheMowgliMan** [comment]
> The problem is, the user then has to download both files and that just adds extra complexity, which we already have too much of?

Why would they have to download both files? Aren't they already included in the ISO?

**Comment by michaeleldar** [comment]
> > The problem is, the user then has to download both files and that just adds extra complexity, which we already have too much of?
> 
> Why would they have to download both files? Aren't they already included in the ISO?

oh right there's an iso...
But in the nightly build thing you would have to download both.

**Comment by TheMowgliMan** [comment]
That's for testers and people who know what they're doing. A little extra
work there isn't a big issue (especially if it's downloading one extra
small python file). If you're worried about it, we can supply them all in a
.zip or something.

**Comment by michaeleldar** [comment]
Okay, merging. Can someone test this as I might not have time to.

**Pull request merged**
